baseurl = "/"
languageCode = "en-us"
title = "Incubaid - Deliver IT as Energy!"
themesDir = "themes"
theme = "landing"
contentdir = "content"
staticdir = "static"
publishdir = "site"
relativeURLs = true
pluralizeListTitles = false

[permalinks]
    post = "/:filename"
    contact-us = "/:filename"


[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Introduction"
    url  = "/introduction"
    weight = 2

[[menu.main]]
    name = "Current Projects"
    identifier = "cprojects"
    weight = 3

[[menu.main]]
    name = "Human Energy Token"
    parent = "cprojects"
    url = "/currentprojects/HumanEnergyToken"

[[menu.main]]
    name = "Rivine.io"
    parent = "cprojects"
    url = "/currentprojects/jimber"

[[menu.main]]
    name = "ThreeFoldTech"
    parent = "cprojects"
    url = "/currentprojects/threefoldtech"

[[menu.main]]
    name = "ThreeFoldFoundation"
    parent = "cprojects"
    url = "/currentprojects/threefoldfoundation"


[[menu.main]]
    name = "Exits"
    identifier = "exits"
    weight = 4

[[menu.main]]
    name = "Amplidata"
    parent = "exits"
    url  = "/exits/Amplidata/"

[[menu.main]]
    name = "Dacentec"
    parent = "exits"
    url  = "/exits/Dacentec/"

[[menu.main]]
    name = "DataCenterTech"
    parent = "exits"
    url  = "/exits/DataCenterTech/"

[[menu.main]]
    name = "Dedigate"
    parent = "exits"
    url  = "/exits/Dedigate/"

[[menu.main]]
    name = "Hostbasket"
    parent = "exits"
    url = "/exits/Hostbasket/"

[[menu.main]]
    name = "Q-Layer"
    parent = "exits"
    url = "/exits/Q-Layer/"

[[menu.main]]
    name = "Virtualbox"
    parent = "exits"
    url = "/exits/Virtualbox/"


[[menu.main]]
    name = "Former Projects"
    identifier = "fprojects"
    weight = 5

[[menu.main]]
    name = "Green IT Globe"
    parent = "fprojects"
    url = "/formerprojects/green-it-globe/"

[[menu.main]]
    name = "Rogerthat"
    parent = "fprojects"
    url = "/formerprojects/Rogerthat/"

[[menu.main]]
    name = "Awingu"
    parent = "fprojects"
    url = "/formerprojects/Awingu/"

[[menu.main]]
    name = "Racktivity"
    parent = "fprojects"
    url = "/formerprojects/Racktivity/"

[[menu.main]]
    name = "Open vStorage"
    parent = "fprojects"
    url = "/formerprojects/Open-vStorage/"

[[menu.main]]
    name = "Itsyou.online"
    parent = "fprojects"
    url = "/formerprojects/Itsyou.online/"

[[menu.main]]
    name = "Company"
    identifier = "company"
    weight = 6

[[menu.main]]
    name = "About The Company"
    parent = "company"
    url = "/company/About-The-Company/"

[[menu.main]]
    name = "Leadership"
    parent = "company"
    url = "/company/Management-Team/"

[[menu.main]]
    name = "Contact Us"
    url  = "/contact-us"
    weight = 7